import { Easing, interpolate } from "remotion";
import type { Animation } from "./types";

export const getAnimationProgress = (
  animation: Animation,
    localMs: number,
    ) => {
    

        return interpolate(
            localMs,
                [animation.startMs, animation.endMs],
                    [0, 1],
                        {
                              extrapolateLeft: "clamp",
                                    extrapolateRight: "clamp",
                                          easing: Easing.out(Easing.cubic),
                                              },
                                                );
                                                };

                                                export const getAnimationStyle = (
                                                  animation: Animation | undefined,
                                                    localMs: number,
                                                    ) => {
                                                      if (!animation) {
                                                          return {
                                                                opacity: 1,
                                                                      transform: "translate(0px, 0px) scale(1) rotate(0deg)",
                                                                            filter: "blur(0px)",
                                                                                };
                                                                                  }

                                                                                    const progress = getAnimationProgress(animation, localMs);

                                                                                      switch (animation.type) {
                                                                                          case "fade":
                                                                                                return {
                                                                                                        opacity: progress,
                                                                                                                transform: "translate(0px, 0px) scale(1) rotate(0deg)",
                                                                                                                        filter: "blur(0px)",
                                                                                                                              };

                                                                                                                                  case "slide":
                                                                                                                                        return {
                                                                                                                                                opacity: progress,
                                                                                                                                                        transform: `translate(${(animation.x ?? 0) * (1 - progress)}px, ${
                                                                                                                                                                  (animation.y ?? 40) * (1 - progress)
                                                                                                                                                                          }px) scale(1) rotate(0deg)`,
                                                                                                                                                                                  filter: "blur(0px)",
                                                                                                                                                                                        };

                                                                                                                                                                                            case "scale": {
                                                                                                                                                                                                  const from = animation.from ?? 0.85;
                                                                                                                                                                                                        const to = animation.to ?? 1;

                                                                                                                                                                                                              const scale = interpolate(progress, [0, 1], [from, to]);

                                                                                                                                                                                                                    return {
                                                                                                                                                                                                                            opacity: progress,
                                                                                                                                                                                                                                    transform: `translate(0px, 0px) scale(${scale}) rotate(0deg)`,
                                                                                                                                                                                                                                            filter: "blur(0px)",
                                                                                                                                                                                                                                                  };
                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                          case "pop": {
                                                                                                                                                                                                                                                                const scale = interpolate(
                                                                                                                                                                                                                                                                        progress,
                                                                                                                                                                                                                                                                                [0, 0.65, 1],
                                                                                                                                                                                                                                                                                        [0.6, 1.08, 1],
                                                                                                                                                                                                                                                                                              );

                                                                                                                                                                                                                                                                                                    return {
                                                                                                                                                                                                                                                                                                            opacity: progress,
                                                                                                                                                                                                                                                                                                                    transform: `translate(0px, 0px) scale(${scale}) rotate(0deg)`,
                                                                                                                                                                                                                                                                                                                            filter: "blur(0px)",
                                                                                                                                                                                                                                                                                                                                  };
                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                          case "float": {
                                                                                                                                                                                                                                                                                                                                                const distance = animation.intensity ?? 12;

                                                                                                                                                                                                                                                                                                                                                      const y = Math.sin(progress * Math.PI * 2) * distance;

                                                                                                                                                                                                                                                                                                                                                            return {
                                                                                                                                                                                                                                                                                                                                                                    opacity: 1,
                                                                                                                                                                                                                                                                                                                                                                            transform: `translate(0px, ${y}px) scale(1) rotate(0deg)`,
                                                                                                                                                                                                                                                                                                                                                                                    filter: "blur(0px)",
                                                                                                                                                                                                                                                                                                                                                                                          };
                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                  case "bounce": {
                                                                                                                                                                                                                                                                                                                                                                                                        const bounce = Math.sin(progress * Math.PI * 3) * 8 * (1 - progress);

                                                                                                                                                                                                                                                                                                                                                                                                              return {
                                                                                                                                                                                                                                                                                                                                                                                                                      opacity: progress,
                                                                                                                                                                                                                                                                                                                                                                                                                              transform: `translate(0px, ${-Math.abs(bounce)}px) scale(1) rotate(0deg)`,
                                                                                                                                                                                                                                                                                                                                                                                                                                      filter: "blur(0px)",
                                                                                                                                                                                                                                                                                                                                                                                                                                            };
                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                    case "rotate": {
                                                                                                                                                                                                                                                                                                                                                                                                                                                          const degrees = animation.to ?? 8;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                const rotation = interpolate(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        progress,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                [0, 1],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        [animation.from ?? -degrees, degrees],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            opacity: 1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    transform: `translate(0px, 0px) scale(1) rotate(${rotation}deg)`,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            filter: "blur(0px)",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          case "blur": {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const blur = interpolate(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        progress,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                [0, 1],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        [animation.from ?? 12, animation.to ?? 0],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            opacity: 1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    transform: "translate(0px, 0px) scale(1) rotate(0deg)",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            filter: `blur(${blur}px)`,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          default:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        opacity: 1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                transform: "translate(0px, 0px) scale(1) rotate(0deg)",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        filter: "blur(0px)",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                };